CREATE USER HR IDENTIFIED BY hr;
GRANT CREATE SESSION TO HR;
GRANT CREATE TABLE TO HR;
GRANT CREATE SEQUENCE TO HR;
GRANT UNLIMITED TABLESPACE TO HR;
GRANT CONNECT, RESOURCE TO HR;
GRANT CREATE VIEW TO HR;
ALTER USER HR ACCOUNT UNLOCK;
ALTER USER HR IDENTIFIED BY hr;